// <auto-generated />
namespace Project_IA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ay7aga : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ay7aga));
        
        string IMigrationMetadata.Id
        {
            get { return "202105301434274_ay7aga"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
