// <auto-generated />
namespace Project_IA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PostStatus : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PostStatus));
        
        string IMigrationMetadata.Id
        {
            get { return "202106062100083_PostStatus"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
